# Generated by Django 5.2.4 on 2025-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects')),
                ('live_url', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
